[package]
name = "nightcycle/constraint-util"
description = "A utility for working with roblox constraints."
version = "1.0.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Maid = "nightcycle/maid@1.1.1"
